run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gas
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - exportloopref
    - govet
  disable:
    - depguard
    - dupl
    - gocyclo
    - lll
    - prealloc
    - gosec # TODO: enable it
    - unparam
    - revive
  fast: false

issues:
  exclude-rules:
    - path: php/parser
      linters:
        - gocritic
        - revive
    - path: cmd/stubs/phpstorm_stubs.go
      linters:
        - gofmt
  exclude-dirs:
    - php/parser/scanner/scanner.go
    - php/parser/scanner/lexer_tokens.go
    - php/parser/scanner/lexer.go
    - php/parser/printer/printer.go
    - php/parser/printer/pretty_printer.go
