run:
  deadline: 3m
  skip-files:
    - php/parser/scanner/scanner.go
    - php/parser/scanner/lexer_tokens.go
    - php/parser/scanner/lexer.go
    - php/parser/printer/printer.go
    - php/parser/printer/pretty_printer.go

linters:
  enable:
    - deadcode
    - gas
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - scopelint
  disable:
    - depguard
    - dupl
    - gocyclo
    - interfacer
    - lll
    - maligned
    - prealloc
    - gosec
  fast: false
  linters:
    enable:
      - gocritic
linters-settings:
  gocritic:
    enabled-checks:
      - appendAssign
      - appendCombine
      - argOrder
      - assignOp
      - badCall
      - badCond
      - badRegexp
      - boolExprSimplify
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deferUnlambda
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - elseif
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - filepathJoin
      - flagDeref
      - flagName
      - ifElseChain
      - importShadow
      - indexAlloc
      - initClause
      - mapKey
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - offBy1
      - rangeExprCopy
      - regexpMust
      - regexpPattern
      - regexpSimplify
      - ruleguard
#      - singleCaseSwitch
      - sloppyLen
      - sloppyReassign
      - sloppyTypeAssert
      - sortSlice
      - stringXbytes
      - switchTrue
      - truncateCmp
      - typeAssertChain
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlabelStmt
      - unlambda
      - unnamedResult
      - unnecessaryBlock
      - unslice
      - valSwap
      - weakCond
      - whyNoLint
      - wrapperFunc
      - yodaStyleExpr
    settings:
      ruleguard:
        rules: "rules.go"

issues:
  exclude-rules:
    - path: php/parser
      linters:
        - gocritic
        - golint
