// Code generated by "stringer -type=ExprKind -trimprefix=Expr"; DO NOT EDIT.

package phpdoc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExprInvalid-0]
	_ = x[ExprUnknown-1]
	_ = x[ExprName-2]
	_ = x[ExprClass-3]
	_ = x[ExprMember-4]
	_ = x[ExprSpecialName-5]
	_ = x[ExprInt-6]
	_ = x[ExprKeyVal-7]
	_ = x[ExprMemberType-8]
	_ = x[ExprArray-9]
	_ = x[ExprParen-10]
	_ = x[ExprNullable-11]
	_ = x[ExprOptional-12]
	_ = x[ExprNot-13]
	_ = x[ExprUnion-14]
	_ = x[ExprInter-15]
	_ = x[ExprGeneric-16]
	_ = x[ExprTypedCallable-17]
}

const _ExprKind_name = "InvalidUnknownNameClassMemberSpecialNameIntKeyValMemberTypeArrayParenNullableOptionalNotUnionInterGenericTypedCallable"

var _ExprKind_index = [...]uint8{0, 7, 14, 18, 23, 29, 40, 43, 49, 59, 64, 69, 77, 85, 88, 93, 98, 105, 118}

func (i ExprKind) String() string {
	if i >= ExprKind(len(_ExprKind_index)-1) {
		return "ExprKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExprKind_name[_ExprKind_index[i]:_ExprKind_index[i+1]]
}
