// Code generated by "stringer -type=ExprKind -trimprefix=Expr"; DO NOT EDIT.

package phpdoc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExprInvalid-0]
	_ = x[ExprUnknown-1]
	_ = x[ExprName-2]
	_ = x[ExprSpecialName-3]
	_ = x[ExprInt-4]
	_ = x[ExprKeyVal-5]
	_ = x[ExprArray-6]
	_ = x[ExprParen-7]
	_ = x[ExprNullable-8]
	_ = x[ExprOptional-9]
	_ = x[ExprNot-10]
	_ = x[ExprUnion-11]
	_ = x[ExprInter-12]
	_ = x[ExprGeneric-13]
	_ = x[ExprTypedCallable-14]
}

const _ExprKind_name = "InvalidUnknownNameSpecialNameIntKeyValArrayParenNullableOptionalNotUnionInterGenericTypedCallable"

var _ExprKind_index = [...]uint8{0, 7, 14, 18, 29, 32, 38, 43, 48, 56, 64, 67, 72, 77, 84, 97}

func (i ExprKind) String() string {
	if i >= ExprKind(len(_ExprKind_index)-1) {
		return "ExprKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExprKind_name[_ExprKind_index[i]:_ExprKind_index[i+1]]
}
