// Code generated by the `ir/codegen` package. DO NOT EDIT.
package ir

import (
	"fmt"
)

type NodeKind int

const (
	KindAnonClassExpr NodeKind = iota
	KindArgument
	KindArrayDimFetchExpr
	KindArrayExpr
	KindArrayItemExpr
	KindArrowFunctionExpr
	KindAssign
	KindAssignBitwiseAnd
	KindAssignBitwiseOr
	KindAssignBitwiseXor
	KindAssignCoalesce
	KindAssignConcat
	KindAssignDiv
	KindAssignMinus
	KindAssignMod
	KindAssignMul
	KindAssignPlus
	KindAssignPow
	KindAssignReference
	KindAssignShiftLeft
	KindAssignShiftRight
	KindBadString
	KindBitwiseAndExpr
	KindBitwiseNotExpr
	KindBitwiseOrExpr
	KindBitwiseXorExpr
	KindBooleanAndExpr
	KindBooleanNotExpr
	KindBooleanOrExpr
	KindBreakStmt
	KindCaseStmt
	KindCatchStmt
	KindClassConstFetchExpr
	KindClassConstListStmt
	KindClassExtendsStmt
	KindClassImplementsStmt
	KindClassMethodStmt
	KindClassStmt
	KindCloneExpr
	KindClosureExpr
	KindClosureUseExpr
	KindCoalesceExpr
	KindConcatExpr
	KindConstFetchExpr
	KindConstListStmt
	KindConstantStmt
	KindContinueStmt
	KindDeclareStmt
	KindDefaultStmt
	KindDivExpr
	KindDnumber
	KindDoStmt
	KindEchoStmt
	KindElseIfStmt
	KindElseStmt
	KindEmptyExpr
	KindEncapsed
	KindEncapsedStringPart
	KindEqualExpr
	KindErrorSuppressExpr
	KindEvalExpr
	KindExitExpr
	KindExpressionStmt
	KindFinallyStmt
	KindForStmt
	KindForeachStmt
	KindFunctionCallExpr
	KindFunctionStmt
	KindGlobalStmt
	KindGotoStmt
	KindGreaterExpr
	KindGreaterOrEqualExpr
	KindGroupUseStmt
	KindHaltCompilerStmt
	KindHeredoc
	KindIdenticalExpr
	KindIdentifier
	KindIfStmt
	KindImportExpr
	KindInlineHTMLStmt
	KindInstanceOfExpr
	KindInterfaceExtendsStmt
	KindInterfaceStmt
	KindIssetExpr
	KindLabelStmt
	KindListExpr
	KindLnumber
	KindLogicalAndExpr
	KindLogicalOrExpr
	KindLogicalXorExpr
	KindMagicConstant
	KindMethodCallExpr
	KindMinusExpr
	KindModExpr
	KindMulExpr
	KindName
	KindNamespaceStmt
	KindNewExpr
	KindNopStmt
	KindNotEqualExpr
	KindNotIdenticalExpr
	KindNullable
	KindParameter
	KindParenExpr
	KindPlusExpr
	KindPostDecExpr
	KindPostIncExpr
	KindPowExpr
	KindPreDecExpr
	KindPreIncExpr
	KindPrintExpr
	KindPropertyFetchExpr
	KindPropertyListStmt
	KindPropertyStmt
	KindReferenceExpr
	KindReturnStmt
	KindRoot
	KindShellExecExpr
	KindShiftLeftExpr
	KindShiftRightExpr
	KindSimpleVar
	KindSmallerExpr
	KindSmallerOrEqualExpr
	KindSpaceshipExpr
	KindStaticCallExpr
	KindStaticPropertyFetchExpr
	KindStaticStmt
	KindStaticVarStmt
	KindStmtList
	KindString
	KindSwitchStmt
	KindTernaryExpr
	KindThrowStmt
	KindTraitAdaptationListStmt
	KindTraitMethodRefStmt
	KindTraitStmt
	KindTraitUseAliasStmt
	KindTraitUsePrecedenceStmt
	KindTraitUseStmt
	KindTryStmt
	KindTypeCastExpr
	KindUnaryMinusExpr
	KindUnaryPlusExpr
	KindUnsetCastExpr
	KindUnsetStmt
	KindUseListStmt
	KindUseStmt
	KindVar
	KindWhileStmt
	KindYieldExpr
	KindYieldFromExpr

	NumKinds
)

func GetNodeKind(x Node) NodeKind {
	switch x := x.(type) {
	case *AnonClassExpr:
		return KindAnonClassExpr
	case *Argument:
		return KindArgument
	case *ArrayDimFetchExpr:
		return KindArrayDimFetchExpr
	case *ArrayExpr:
		return KindArrayExpr
	case *ArrayItemExpr:
		return KindArrayItemExpr
	case *ArrowFunctionExpr:
		return KindArrowFunctionExpr
	case *Assign:
		return KindAssign
	case *AssignBitwiseAnd:
		return KindAssignBitwiseAnd
	case *AssignBitwiseOr:
		return KindAssignBitwiseOr
	case *AssignBitwiseXor:
		return KindAssignBitwiseXor
	case *AssignCoalesce:
		return KindAssignCoalesce
	case *AssignConcat:
		return KindAssignConcat
	case *AssignDiv:
		return KindAssignDiv
	case *AssignMinus:
		return KindAssignMinus
	case *AssignMod:
		return KindAssignMod
	case *AssignMul:
		return KindAssignMul
	case *AssignPlus:
		return KindAssignPlus
	case *AssignPow:
		return KindAssignPow
	case *AssignReference:
		return KindAssignReference
	case *AssignShiftLeft:
		return KindAssignShiftLeft
	case *AssignShiftRight:
		return KindAssignShiftRight
	case *BadString:
		return KindBadString
	case *BitwiseAndExpr:
		return KindBitwiseAndExpr
	case *BitwiseNotExpr:
		return KindBitwiseNotExpr
	case *BitwiseOrExpr:
		return KindBitwiseOrExpr
	case *BitwiseXorExpr:
		return KindBitwiseXorExpr
	case *BooleanAndExpr:
		return KindBooleanAndExpr
	case *BooleanNotExpr:
		return KindBooleanNotExpr
	case *BooleanOrExpr:
		return KindBooleanOrExpr
	case *BreakStmt:
		return KindBreakStmt
	case *CaseStmt:
		return KindCaseStmt
	case *CatchStmt:
		return KindCatchStmt
	case *ClassConstFetchExpr:
		return KindClassConstFetchExpr
	case *ClassConstListStmt:
		return KindClassConstListStmt
	case *ClassExtendsStmt:
		return KindClassExtendsStmt
	case *ClassImplementsStmt:
		return KindClassImplementsStmt
	case *ClassMethodStmt:
		return KindClassMethodStmt
	case *ClassStmt:
		return KindClassStmt
	case *CloneExpr:
		return KindCloneExpr
	case *ClosureExpr:
		return KindClosureExpr
	case *ClosureUseExpr:
		return KindClosureUseExpr
	case *CoalesceExpr:
		return KindCoalesceExpr
	case *ConcatExpr:
		return KindConcatExpr
	case *ConstFetchExpr:
		return KindConstFetchExpr
	case *ConstListStmt:
		return KindConstListStmt
	case *ConstantStmt:
		return KindConstantStmt
	case *ContinueStmt:
		return KindContinueStmt
	case *DeclareStmt:
		return KindDeclareStmt
	case *DefaultStmt:
		return KindDefaultStmt
	case *DivExpr:
		return KindDivExpr
	case *Dnumber:
		return KindDnumber
	case *DoStmt:
		return KindDoStmt
	case *EchoStmt:
		return KindEchoStmt
	case *ElseIfStmt:
		return KindElseIfStmt
	case *ElseStmt:
		return KindElseStmt
	case *EmptyExpr:
		return KindEmptyExpr
	case *Encapsed:
		return KindEncapsed
	case *EncapsedStringPart:
		return KindEncapsedStringPart
	case *EqualExpr:
		return KindEqualExpr
	case *ErrorSuppressExpr:
		return KindErrorSuppressExpr
	case *EvalExpr:
		return KindEvalExpr
	case *ExitExpr:
		return KindExitExpr
	case *ExpressionStmt:
		return KindExpressionStmt
	case *FinallyStmt:
		return KindFinallyStmt
	case *ForStmt:
		return KindForStmt
	case *ForeachStmt:
		return KindForeachStmt
	case *FunctionCallExpr:
		return KindFunctionCallExpr
	case *FunctionStmt:
		return KindFunctionStmt
	case *GlobalStmt:
		return KindGlobalStmt
	case *GotoStmt:
		return KindGotoStmt
	case *GreaterExpr:
		return KindGreaterExpr
	case *GreaterOrEqualExpr:
		return KindGreaterOrEqualExpr
	case *GroupUseStmt:
		return KindGroupUseStmt
	case *HaltCompilerStmt:
		return KindHaltCompilerStmt
	case *Heredoc:
		return KindHeredoc
	case *IdenticalExpr:
		return KindIdenticalExpr
	case *Identifier:
		return KindIdentifier
	case *IfStmt:
		return KindIfStmt
	case *ImportExpr:
		return KindImportExpr
	case *InlineHTMLStmt:
		return KindInlineHTMLStmt
	case *InstanceOfExpr:
		return KindInstanceOfExpr
	case *InterfaceExtendsStmt:
		return KindInterfaceExtendsStmt
	case *InterfaceStmt:
		return KindInterfaceStmt
	case *IssetExpr:
		return KindIssetExpr
	case *LabelStmt:
		return KindLabelStmt
	case *ListExpr:
		return KindListExpr
	case *Lnumber:
		return KindLnumber
	case *LogicalAndExpr:
		return KindLogicalAndExpr
	case *LogicalOrExpr:
		return KindLogicalOrExpr
	case *LogicalXorExpr:
		return KindLogicalXorExpr
	case *MagicConstant:
		return KindMagicConstant
	case *MethodCallExpr:
		return KindMethodCallExpr
	case *MinusExpr:
		return KindMinusExpr
	case *ModExpr:
		return KindModExpr
	case *MulExpr:
		return KindMulExpr
	case *Name:
		return KindName
	case *NamespaceStmt:
		return KindNamespaceStmt
	case *NewExpr:
		return KindNewExpr
	case *NopStmt:
		return KindNopStmt
	case *NotEqualExpr:
		return KindNotEqualExpr
	case *NotIdenticalExpr:
		return KindNotIdenticalExpr
	case *Nullable:
		return KindNullable
	case *Parameter:
		return KindParameter
	case *ParenExpr:
		return KindParenExpr
	case *PlusExpr:
		return KindPlusExpr
	case *PostDecExpr:
		return KindPostDecExpr
	case *PostIncExpr:
		return KindPostIncExpr
	case *PowExpr:
		return KindPowExpr
	case *PreDecExpr:
		return KindPreDecExpr
	case *PreIncExpr:
		return KindPreIncExpr
	case *PrintExpr:
		return KindPrintExpr
	case *PropertyFetchExpr:
		return KindPropertyFetchExpr
	case *PropertyListStmt:
		return KindPropertyListStmt
	case *PropertyStmt:
		return KindPropertyStmt
	case *ReferenceExpr:
		return KindReferenceExpr
	case *ReturnStmt:
		return KindReturnStmt
	case *Root:
		return KindRoot
	case *ShellExecExpr:
		return KindShellExecExpr
	case *ShiftLeftExpr:
		return KindShiftLeftExpr
	case *ShiftRightExpr:
		return KindShiftRightExpr
	case *SimpleVar:
		return KindSimpleVar
	case *SmallerExpr:
		return KindSmallerExpr
	case *SmallerOrEqualExpr:
		return KindSmallerOrEqualExpr
	case *SpaceshipExpr:
		return KindSpaceshipExpr
	case *StaticCallExpr:
		return KindStaticCallExpr
	case *StaticPropertyFetchExpr:
		return KindStaticPropertyFetchExpr
	case *StaticStmt:
		return KindStaticStmt
	case *StaticVarStmt:
		return KindStaticVarStmt
	case *StmtList:
		return KindStmtList
	case *String:
		return KindString
	case *SwitchStmt:
		return KindSwitchStmt
	case *TernaryExpr:
		return KindTernaryExpr
	case *ThrowStmt:
		return KindThrowStmt
	case *TraitAdaptationListStmt:
		return KindTraitAdaptationListStmt
	case *TraitMethodRefStmt:
		return KindTraitMethodRefStmt
	case *TraitStmt:
		return KindTraitStmt
	case *TraitUseAliasStmt:
		return KindTraitUseAliasStmt
	case *TraitUsePrecedenceStmt:
		return KindTraitUsePrecedenceStmt
	case *TraitUseStmt:
		return KindTraitUseStmt
	case *TryStmt:
		return KindTryStmt
	case *TypeCastExpr:
		return KindTypeCastExpr
	case *UnaryMinusExpr:
		return KindUnaryMinusExpr
	case *UnaryPlusExpr:
		return KindUnaryPlusExpr
	case *UnsetCastExpr:
		return KindUnsetCastExpr
	case *UnsetStmt:
		return KindUnsetStmt
	case *UseListStmt:
		return KindUseListStmt
	case *UseStmt:
		return KindUseStmt
	case *Var:
		return KindVar
	case *WhileStmt:
		return KindWhileStmt
	case *YieldExpr:
		return KindYieldExpr
	case *YieldFromExpr:
		return KindYieldFromExpr
	default:
		panic(fmt.Sprintf(`unhandled type %T`, x))
	}
}
