// Code generated by the `ir/codegen` package. DO NOT EDIT.
package ir

func (n *AnonClassExpr) IterateTokens(cb func(*Token) bool) {
	if n.ClassTkn != nil {
		if !cb(n.ClassTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ExtendsTkn != nil {
		if !cb(n.ExtendsTkn) {
			return
		}
	}
	if n.ImplementsTkn != nil {
		if !cb(n.ImplementsTkn) {
			return
		}
	}
	for _, tk := range n.ImplementsSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *Argument) IterateTokens(cb func(*Token) bool) {
	if n.VariadicTkn != nil {
		if !cb(n.VariadicTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
}

func (n *ArrayDimFetchExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpenBracketTkn != nil {
		if !cb(n.OpenBracketTkn) {
			return
		}
	}
	if n.CloseBracketTkn != nil {
		if !cb(n.CloseBracketTkn) {
			return
		}
	}
}

func (n *ArrayExpr) IterateTokens(cb func(*Token) bool) {
	if n.ArrayTkn != nil {
		if !cb(n.ArrayTkn) {
			return
		}
	}
	if n.OpenBracketTkn != nil {
		if !cb(n.OpenBracketTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseBracketTkn != nil {
		if !cb(n.CloseBracketTkn) {
			return
		}
	}
}

func (n *ArrayItemExpr) IterateTokens(cb func(*Token) bool) {
	if n.EllipsisTkn != nil {
		if !cb(n.EllipsisTkn) {
			return
		}
	}
	if n.DoubleArrowTkn != nil {
		if !cb(n.DoubleArrowTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
}

func (n *ArrowFunctionExpr) IterateTokens(cb func(*Token) bool) {
	if n.StaticTkn != nil {
		if !cb(n.StaticTkn) {
			return
		}
	}
	if n.FnTkn != nil {
		if !cb(n.FnTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.DoubleArrowTkn != nil {
		if !cb(n.DoubleArrowTkn) {
			return
		}
	}
}

func (n *Assign) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignBitwiseAnd) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignBitwiseOr) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignBitwiseXor) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignCoalesce) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignConcat) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignDiv) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignMinus) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignMod) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignMul) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignPlus) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignPow) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignReference) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignShiftLeft) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *AssignShiftRight) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *BadString) IterateTokens(cb func(*Token) bool) {
	if n.MinusTkn != nil {
		if !cb(n.MinusTkn) {
			return
		}
	}
	if n.StringTkn != nil {
		if !cb(n.StringTkn) {
			return
		}
	}
}

func (n *BitwiseAndExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *BitwiseNotExpr) IterateTokens(cb func(*Token) bool) {
	if n.TildaTkn != nil {
		if !cb(n.TildaTkn) {
			return
		}
	}
}

func (n *BitwiseOrExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *BitwiseXorExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *BooleanAndExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *BooleanNotExpr) IterateTokens(cb func(*Token) bool) {
	if n.ExclamationTkn != nil {
		if !cb(n.ExclamationTkn) {
			return
		}
	}
}

func (n *BooleanOrExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *BreakStmt) IterateTokens(cb func(*Token) bool) {
	if n.BreakTkn != nil {
		if !cb(n.BreakTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *CaseListStmt) IterateTokens(cb func(*Token) bool) {
}

func (n *CaseStmt) IterateTokens(cb func(*Token) bool) {
	if n.CaseTkn != nil {
		if !cb(n.CaseTkn) {
			return
		}
	}
	if n.CaseSeparatorTkn != nil {
		if !cb(n.CaseSeparatorTkn) {
			return
		}
	}
}

func (n *CatchStmt) IterateTokens(cb func(*Token) bool) {
	if n.CatchTkn != nil {
		if !cb(n.CatchTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *ClassConstFetchExpr) IterateTokens(cb func(*Token) bool) {
	if n.DoubleColonTkn != nil {
		if !cb(n.DoubleColonTkn) {
			return
		}
	}
}

func (n *ClassConstListStmt) IterateTokens(cb func(*Token) bool) {
	if n.ConstTkn != nil {
		if !cb(n.ConstTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *ClassExtendsStmt) IterateTokens(cb func(*Token) bool) {
}

func (n *ClassImplementsStmt) IterateTokens(cb func(*Token) bool) {
}

func (n *ClassMethodStmt) IterateTokens(cb func(*Token) bool) {
	if n.FunctionTkn != nil {
		if !cb(n.FunctionTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
}

func (n *ClassStmt) IterateTokens(cb func(*Token) bool) {
	if n.ClassTkn != nil {
		if !cb(n.ClassTkn) {
			return
		}
	}
	if n.ExtendsTkn != nil {
		if !cb(n.ExtendsTkn) {
			return
		}
	}
	if n.ImplementsTkn != nil {
		if !cb(n.ImplementsTkn) {
			return
		}
	}
	for _, tk := range n.ImplementsSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *CloneExpr) IterateTokens(cb func(*Token) bool) {
	if n.CloneTkn != nil {
		if !cb(n.CloneTkn) {
			return
		}
	}
}

func (n *ClosureExpr) IterateTokens(cb func(*Token) bool) {
	if n.StaticTkn != nil {
		if !cb(n.StaticTkn) {
			return
		}
	}
	if n.FunctionTkn != nil {
		if !cb(n.FunctionTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.UseTkn != nil {
		if !cb(n.UseTkn) {
			return
		}
	}
	if n.UseOpenParenthesisTkn != nil {
		if !cb(n.UseOpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.UseSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.UseCloseParenthesisTkn != nil {
		if !cb(n.UseCloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *ClosureUseExpr) IterateTokens(cb func(*Token) bool) {
}

func (n *CoalesceExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *ConcatExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *ConstFetchExpr) IterateTokens(cb func(*Token) bool) {
}

func (n *ConstListStmt) IterateTokens(cb func(*Token) bool) {
	if n.ConstTkn != nil {
		if !cb(n.ConstTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *ConstantStmt) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *ContinueStmt) IterateTokens(cb func(*Token) bool) {
	if n.ContinueTkn != nil {
		if !cb(n.ContinueTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *DeclareStmt) IterateTokens(cb func(*Token) bool) {
	if n.DeclareTkn != nil {
		if !cb(n.DeclareTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.EndDeclareTkn != nil {
		if !cb(n.EndDeclareTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *DefaultStmt) IterateTokens(cb func(*Token) bool) {
	if n.DefaultTkn != nil {
		if !cb(n.DefaultTkn) {
			return
		}
	}
	if n.CaseSeparatorTkn != nil {
		if !cb(n.CaseSeparatorTkn) {
			return
		}
	}
}

func (n *DivExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *Dnumber) IterateTokens(cb func(*Token) bool) {
	if n.NumberTkn != nil {
		if !cb(n.NumberTkn) {
			return
		}
	}
}

func (n *DoStmt) IterateTokens(cb func(*Token) bool) {
	if n.DoTkn != nil {
		if !cb(n.DoTkn) {
			return
		}
	}
	if n.WhileTkn != nil {
		if !cb(n.WhileTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *EchoStmt) IterateTokens(cb func(*Token) bool) {
	if n.EchoTkn != nil {
		if !cb(n.EchoTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *ElseIfStmt) IterateTokens(cb func(*Token) bool) {
	if n.ElseIfTkn != nil {
		if !cb(n.ElseIfTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
}

func (n *ElseStmt) IterateTokens(cb func(*Token) bool) {
	if n.ElseTkn != nil {
		if !cb(n.ElseTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
}

func (n *EmptyExpr) IterateTokens(cb func(*Token) bool) {
	if n.EmptyTkn != nil {
		if !cb(n.EmptyTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *Encapsed) IterateTokens(cb func(*Token) bool) {
	if n.OpenQuoteTkn != nil {
		if !cb(n.OpenQuoteTkn) {
			return
		}
	}
	if n.CloseQuoteTkn != nil {
		if !cb(n.CloseQuoteTkn) {
			return
		}
	}
}

func (n *EncapsedStringPart) IterateTokens(cb func(*Token) bool) {
	if n.EncapsedStrTkn != nil {
		if !cb(n.EncapsedStrTkn) {
			return
		}
	}
}

func (n *EqualExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *ErrorSuppressExpr) IterateTokens(cb func(*Token) bool) {
	if n.AtTkn != nil {
		if !cb(n.AtTkn) {
			return
		}
	}
}

func (n *EvalExpr) IterateTokens(cb func(*Token) bool) {
	if n.EvalTkn != nil {
		if !cb(n.EvalTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *ExitExpr) IterateTokens(cb func(*Token) bool) {
	if n.ExitTkn != nil {
		if !cb(n.ExitTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *ExpressionStmt) IterateTokens(cb func(*Token) bool) {
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *FinallyStmt) IterateTokens(cb func(*Token) bool) {
	if n.FinallyTkn != nil {
		if !cb(n.FinallyTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *ForStmt) IterateTokens(cb func(*Token) bool) {
	if n.ForTkn != nil {
		if !cb(n.ForTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.InitSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.InitSemiColonTkn != nil {
		if !cb(n.InitSemiColonTkn) {
			return
		}
	}
	for _, tk := range n.CondSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CondSemiColonTkn != nil {
		if !cb(n.CondSemiColonTkn) {
			return
		}
	}
	for _, tk := range n.LoopSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.EndForTkn != nil {
		if !cb(n.EndForTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *ForeachStmt) IterateTokens(cb func(*Token) bool) {
	if n.ForeachTkn != nil {
		if !cb(n.ForeachTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.AsTkn != nil {
		if !cb(n.AsTkn) {
			return
		}
	}
	if n.DoubleArrowTkn != nil {
		if !cb(n.DoubleArrowTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.EndForeachTkn != nil {
		if !cb(n.EndForeachTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *FunctionCallExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *FunctionStmt) IterateTokens(cb func(*Token) bool) {
	if n.FunctionTkn != nil {
		if !cb(n.FunctionTkn) {
			return
		}
	}
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *GlobalStmt) IterateTokens(cb func(*Token) bool) {
	if n.GlobalTkn != nil {
		if !cb(n.GlobalTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *GotoStmt) IterateTokens(cb func(*Token) bool) {
	if n.GotoTkn != nil {
		if !cb(n.GotoTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *GreaterExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *GreaterOrEqualExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *GroupUseStmt) IterateTokens(cb func(*Token) bool) {
	if n.UseTkn != nil {
		if !cb(n.UseTkn) {
			return
		}
	}
	if n.LeadingNsSeparatorTkn != nil {
		if !cb(n.LeadingNsSeparatorTkn) {
			return
		}
	}
	if n.NsSeparatorTkn != nil {
		if !cb(n.NsSeparatorTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *HaltCompilerStmt) IterateTokens(cb func(*Token) bool) {
	if n.HaltCompilerTkn != nil {
		if !cb(n.HaltCompilerTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *Heredoc) IterateTokens(cb func(*Token) bool) {
	if n.OpenHeredocTkn != nil {
		if !cb(n.OpenHeredocTkn) {
			return
		}
	}
	if n.CloseHeredocTkn != nil {
		if !cb(n.CloseHeredocTkn) {
			return
		}
	}
}

func (n *IdenticalExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *Identifier) IterateTokens(cb func(*Token) bool) {
	if n.IdentifierTkn != nil {
		if !cb(n.IdentifierTkn) {
			return
		}
	}
}

func (n *IfStmt) IterateTokens(cb func(*Token) bool) {
	if n.IfTkn != nil {
		if !cb(n.IfTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.EndIfTkn != nil {
		if !cb(n.EndIfTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *ImportExpr) IterateTokens(cb func(*Token) bool) {
	if n.ImportTkn != nil {
		if !cb(n.ImportTkn) {
			return
		}
	}
}

func (n *InlineHTMLStmt) IterateTokens(cb func(*Token) bool) {
	if n.InlineHTMLTkn != nil {
		if !cb(n.InlineHTMLTkn) {
			return
		}
	}
}

func (n *InstanceOfExpr) IterateTokens(cb func(*Token) bool) {
	if n.InstanceOfTkn != nil {
		if !cb(n.InstanceOfTkn) {
			return
		}
	}
}

func (n *InterfaceExtendsStmt) IterateTokens(cb func(*Token) bool) {
	if n.Token != nil {
		if !cb(n.Token) {
			return
		}
	}
}

func (n *InterfaceStmt) IterateTokens(cb func(*Token) bool) {
	if n.InterfaceTkn != nil {
		if !cb(n.InterfaceTkn) {
			return
		}
	}
	if n.ExtendsTkn != nil {
		if !cb(n.ExtendsTkn) {
			return
		}
	}
	for _, tk := range n.ExtendsSeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *IssetExpr) IterateTokens(cb func(*Token) bool) {
	if n.IssetTkn != nil {
		if !cb(n.IssetTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *LabelStmt) IterateTokens(cb func(*Token) bool) {
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
}

func (n *ListExpr) IterateTokens(cb func(*Token) bool) {
	if n.ListTkn != nil {
		if !cb(n.ListTkn) {
			return
		}
	}
	if n.OpenBracketTkn != nil {
		if !cb(n.OpenBracketTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseBracketTkn != nil {
		if !cb(n.CloseBracketTkn) {
			return
		}
	}
}

func (n *Lnumber) IterateTokens(cb func(*Token) bool) {
	if n.NumberTkn != nil {
		if !cb(n.NumberTkn) {
			return
		}
	}
}

func (n *LogicalAndExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *LogicalOrExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *LogicalXorExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *MagicConstant) IterateTokens(cb func(*Token) bool) {
	if n.MagicConstTkn != nil {
		if !cb(n.MagicConstTkn) {
			return
		}
	}
}

func (n *MethodCallExpr) IterateTokens(cb func(*Token) bool) {
	if n.ObjectOperatorTkn != nil {
		if !cb(n.ObjectOperatorTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *MinusExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *ModExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *MulExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *Name) IterateTokens(cb func(*Token) bool) {
}

func (n *NamespaceStmt) IterateTokens(cb func(*Token) bool) {
	if n.NsTkn != nil {
		if !cb(n.NsTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *NewExpr) IterateTokens(cb func(*Token) bool) {
	if n.NewTkn != nil {
		if !cb(n.NewTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *NopStmt) IterateTokens(cb func(*Token) bool) {
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *NotEqualExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *NotIdenticalExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *Nullable) IterateTokens(cb func(*Token) bool) {
	if n.QuestionTkn != nil {
		if !cb(n.QuestionTkn) {
			return
		}
	}
}

func (n *Parameter) IterateTokens(cb func(*Token) bool) {
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
	if n.VariadicTkn != nil {
		if !cb(n.VariadicTkn) {
			return
		}
	}
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *ParenExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *PlusExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *PostDecExpr) IterateTokens(cb func(*Token) bool) {
	if n.DecTkn != nil {
		if !cb(n.DecTkn) {
			return
		}
	}
}

func (n *PostIncExpr) IterateTokens(cb func(*Token) bool) {
	if n.IncTkn != nil {
		if !cb(n.IncTkn) {
			return
		}
	}
}

func (n *PowExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *PreDecExpr) IterateTokens(cb func(*Token) bool) {
	if n.DecTkn != nil {
		if !cb(n.DecTkn) {
			return
		}
	}
}

func (n *PreIncExpr) IterateTokens(cb func(*Token) bool) {
	if n.IncTkn != nil {
		if !cb(n.IncTkn) {
			return
		}
	}
}

func (n *PrintExpr) IterateTokens(cb func(*Token) bool) {
	if n.PrintTkn != nil {
		if !cb(n.PrintTkn) {
			return
		}
	}
}

func (n *PropertyFetchExpr) IterateTokens(cb func(*Token) bool) {
	if n.ObjectOperatorTkn != nil {
		if !cb(n.ObjectOperatorTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *PropertyListStmt) IterateTokens(cb func(*Token) bool) {
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *PropertyStmt) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *ReferenceExpr) IterateTokens(cb func(*Token) bool) {
	if n.AmpersandTkn != nil {
		if !cb(n.AmpersandTkn) {
			return
		}
	}
}

func (n *ReturnStmt) IterateTokens(cb func(*Token) bool) {
	if n.ReturnTkn != nil {
		if !cb(n.ReturnTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *Root) IterateTokens(cb func(*Token) bool) {
	if n.EndTkn != nil {
		if !cb(n.EndTkn) {
			return
		}
	}
}

func (n *ShellExecExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpenBacktickTkn != nil {
		if !cb(n.OpenBacktickTkn) {
			return
		}
	}
	if n.CloseBacktickTkn != nil {
		if !cb(n.CloseBacktickTkn) {
			return
		}
	}
}

func (n *ShiftLeftExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *ShiftRightExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *SimpleVar) IterateTokens(cb func(*Token) bool) {
	if n.DollarTkn != nil {
		if !cb(n.DollarTkn) {
			return
		}
	}
}

func (n *SmallerExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *SmallerOrEqualExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *SpaceshipExpr) IterateTokens(cb func(*Token) bool) {
	if n.OpTkn != nil {
		if !cb(n.OpTkn) {
			return
		}
	}
}

func (n *StaticCallExpr) IterateTokens(cb func(*Token) bool) {
	if n.DoubleColonTkn != nil {
		if !cb(n.DoubleColonTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
}

func (n *StaticPropertyFetchExpr) IterateTokens(cb func(*Token) bool) {
	if n.DoubleColonTkn != nil {
		if !cb(n.DoubleColonTkn) {
			return
		}
	}
}

func (n *StaticStmt) IterateTokens(cb func(*Token) bool) {
	if n.StaticTkn != nil {
		if !cb(n.StaticTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *StaticVarStmt) IterateTokens(cb func(*Token) bool) {
	if n.EqualTkn != nil {
		if !cb(n.EqualTkn) {
			return
		}
	}
}

func (n *StmtList) IterateTokens(cb func(*Token) bool) {
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *String) IterateTokens(cb func(*Token) bool) {
	if n.MinusTkn != nil {
		if !cb(n.MinusTkn) {
			return
		}
	}
	if n.StringTkn != nil {
		if !cb(n.StringTkn) {
			return
		}
	}
}

func (n *SwitchStmt) IterateTokens(cb func(*Token) bool) {
	if n.SwitchTkn != nil {
		if !cb(n.SwitchTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CaseSeparatorTkn != nil {
		if !cb(n.CaseSeparatorTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
	if n.EndSwitchTkn != nil {
		if !cb(n.EndSwitchTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *TernaryExpr) IterateTokens(cb func(*Token) bool) {
	if n.QuestionTkn != nil {
		if !cb(n.QuestionTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
}

func (n *ThrowStmt) IterateTokens(cb func(*Token) bool) {
	if n.ThrowTkn != nil {
		if !cb(n.ThrowTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *TraitAdaptationListStmt) IterateTokens(cb func(*Token) bool) {
}

func (n *TraitMethodRefStmt) IterateTokens(cb func(*Token) bool) {
}

func (n *TraitStmt) IterateTokens(cb func(*Token) bool) {
	if n.TraitTkn != nil {
		if !cb(n.TraitTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *TraitUseAliasStmt) IterateTokens(cb func(*Token) bool) {
	if n.DoubleColonTkn != nil {
		if !cb(n.DoubleColonTkn) {
			return
		}
	}
	if n.AsTkn != nil {
		if !cb(n.AsTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *TraitUsePrecedenceStmt) IterateTokens(cb func(*Token) bool) {
	if n.DoubleColonTkn != nil {
		if !cb(n.DoubleColonTkn) {
			return
		}
	}
	if n.InsteadofTkn != nil {
		if !cb(n.InsteadofTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *TraitUseStmt) IterateTokens(cb func(*Token) bool) {
	if n.UseTkn != nil {
		if !cb(n.UseTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *TryStmt) IterateTokens(cb func(*Token) bool) {
	if n.TryTkn != nil {
		if !cb(n.TryTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *TypeCastExpr) IterateTokens(cb func(*Token) bool) {
	if n.CastTkn != nil {
		if !cb(n.CastTkn) {
			return
		}
	}
}

func (n *UnaryMinusExpr) IterateTokens(cb func(*Token) bool) {
	if n.MinusTkn != nil {
		if !cb(n.MinusTkn) {
			return
		}
	}
}

func (n *UnaryPlusExpr) IterateTokens(cb func(*Token) bool) {
	if n.PlusTkn != nil {
		if !cb(n.PlusTkn) {
			return
		}
	}
}

func (n *UnsetCastExpr) IterateTokens(cb func(*Token) bool) {
	if n.CastTkn != nil {
		if !cb(n.CastTkn) {
			return
		}
	}
}

func (n *UnsetStmt) IterateTokens(cb func(*Token) bool) {
	if n.UnsetTkn != nil {
		if !cb(n.UnsetTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *UseListStmt) IterateTokens(cb func(*Token) bool) {
	if n.UseTkn != nil {
		if !cb(n.UseTkn) {
			return
		}
	}
	for _, tk := range n.SeparatorTkns {
		if !cb(tk) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *UseStmt) IterateTokens(cb func(*Token) bool) {
	if n.NsSeparatorTkn != nil {
		if !cb(n.NsSeparatorTkn) {
			return
		}
	}
	if n.AsTkn != nil {
		if !cb(n.AsTkn) {
			return
		}
	}
}

func (n *Var) IterateTokens(cb func(*Token) bool) {
	if n.DollarTkn != nil {
		if !cb(n.DollarTkn) {
			return
		}
	}
	if n.OpenCurlyBracketTkn != nil {
		if !cb(n.OpenCurlyBracketTkn) {
			return
		}
	}
	if n.CloseCurlyBracketTkn != nil {
		if !cb(n.CloseCurlyBracketTkn) {
			return
		}
	}
}

func (n *WhileStmt) IterateTokens(cb func(*Token) bool) {
	if n.WhileTkn != nil {
		if !cb(n.WhileTkn) {
			return
		}
	}
	if n.OpenParenthesisTkn != nil {
		if !cb(n.OpenParenthesisTkn) {
			return
		}
	}
	if n.CloseParenthesisTkn != nil {
		if !cb(n.CloseParenthesisTkn) {
			return
		}
	}
	if n.ColonTkn != nil {
		if !cb(n.ColonTkn) {
			return
		}
	}
	if n.EndWhileTkn != nil {
		if !cb(n.EndWhileTkn) {
			return
		}
	}
	if n.SemiColonTkn != nil {
		if !cb(n.SemiColonTkn) {
			return
		}
	}
}

func (n *YieldExpr) IterateTokens(cb func(*Token) bool) {
	if n.YieldTkn != nil {
		if !cb(n.YieldTkn) {
			return
		}
	}
	if n.DoubleArrowTkn != nil {
		if !cb(n.DoubleArrowTkn) {
			return
		}
	}
}

func (n *YieldFromExpr) IterateTokens(cb func(*Token) bool) {
	if n.YieldFromTkn != nil {
		if !cb(n.YieldFromTkn) {
			return
		}
	}
}
