name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Set up Go 1.16
        uses: actions/setup-go@v5
        with:
          go-version: 1.16

      - name: Run Tests
        run: make test
